[tool.poetry]
name = "dotfiles"
version = "1.0.0"
description = ""
authors = ["Bruno Semperlotti <bruno.semperlotti@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "8.0.0"

[tool.poetry.dev-dependencies]
ansible-lint = { version = "6.17.0", markers = "platform_system != 'Windows'" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
