[tool.poetry]
name = "workstation-bootstrap"
version = "0.1.0"
description = ""
authors = ["Bruno Semperlotti <bruno.semperlotti@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "^7.4.0"

[tool.poetry.dev-dependencies]
ansible-lint = "^6.8.7"
yamllint = "^1.30.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
