[tool.poetry]
name = "workstation-bootstrap"
version = "0.1.0"
description = ""
authors = ["Bruno Semperlotti <bruno.semperlotti@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
ansible = "^5.7.1"

[tool.poetry.dev-dependencies]
ansible-lint = "^5.3.2"
yamllint = "^1.26.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
