[tool.poetry]
name = "workstation-bootstrap"
version = "0.1.0"
description = ""
authors = ["Bruno Semperlotti <bruno.semperlotti@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
ansible = "^6.0.0"

[tool.poetry.dev-dependencies]
ansible-lint = "^6.3.0"
yamllint = "^1.27.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
