---
cli_tools_config_file: ""

cli_tools_brew_packages:
  - bat # A cat(1) clone with syntax highlighting and Git integration
  - bash # Install newest bash instead of macos outdated 3.2
  - cheat # Interactive cheatsheets on the command-line
  - curl
  - exa # A modern replacement for ls
  - fzf # A command-line fuzzy finder
  - git
  - gnupg
  - hping
  - httpie
  - ipcalc # IP subnet calculator
  - jq
  - jsonnet
  - openssl
  - tig # A text-mode interface for git
  - tmux
  - the_silver_searcher # A code searching tool similar to ack, with a focus on speed.
  - tree
  - wget

cli_tools_linux_packages:
  - curl
  - exa # A modern replacement for ls
  - fzf # A command-line fuzzy finder
  - git
  - gnupg
  - hping3
  - httpie
  - jq
  - jsonnet
  - openssl
  - snapd
  - tmux
  - tree
  - wget
