---
- name: Select macos package
  when: ansible_system == "Darwin"
  set_fact:
    python_packages: "{{ python_brew_packages }}"

- name: Select linux package
  when: ansible_system == "Linux"
  set_fact:
    python_packages: "{{ python_linux_packages }}"

- name: Install python
  package:
    name: "{{ item }}"
    state: latest
  become: "{{ true if ansible_system == 'Linux' else false }}"
  loop: "{{ python_packages }}"
