---
- name: Install brew packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ python_brew_packages }}"

- name: Install pipx packages
  community.general.pipx:
    name: "{{ item }}"
    state: latest
    executable: pipx # Default is "python -m pipx", but we want to use the brew-installed pipx
  loop: "{{ python_pipx_packages }}"
