---
- name: Add default SSH config
  ansible.builtin.blockinfile:
    create: true
    marker: "# {mark} - ANSIBLE MANAGED BLOCK"
    insertafter: EOF
    path: "{{ ansible_env.HOME }}/.ssh/config"
    block: |
      # Add default github config
      Host github.com
        User git
        PreferredAuthentications publickey

      # Host * should always be the last entry has it is the most general matching rule
      Host *
        AddKeysToAgent yes
        UseKeychain yes
        ForwardAgent no
        Compression yes
    mode: "0600"
