---
- name: Install brew packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ zsh_brew_packages }}"

- name: Copy Custom zsh configuration to {{ zsh_config_dir }}
  ansible.builtin.copy:
    src: "./files/config/" # trailing / is important to copy only directory content and not the directory itself
    dest: "{{ zsh_config_dir }}"
    mode: "0600"

- name: Copy Custom zshrc to {{ zsh_config_dir }}
  ansible.builtin.template:
    src: ".zshrc.j2"
    dest: "{{ zsh_config_dir }}/.zshrc"
    mode: "0600"

- name: Copy Custom zprofile to {{ zsh_config_dir }}
  ansible.builtin.template:
    src: ".zprofile.j2"
    dest: "{{ zsh_config_dir }}/.zprofile"
    mode: "0600"

- name: Copy Custom zshenv to {{ zsh_config_dir }}
  ansible.builtin.template:
    src: ".zshenv.j2"
    dest: "{{ zsh_config_dir }}/.zshenv"
    mode: "0600"

- name: Create a symbolic link to custom zshenv
  ansible.builtin.file:
    src: "{{ zsh_config_dir }}/.zshenv"
    dest: "~/.zshenv"
    state: link

- name: Create a symbolic link to custom zsh completions
  ansible.builtin.file:
    src: "{{ zsh_config_dir }}/completions"
    dest: "~/.zshcompletions"
    state: link
