---
- name: Install brew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  loop: "{{ aws_brew_packages }}"

- name: Copy custom configuration to {{ xdg_config_home }}
  ansible.builtin.copy:
    src: "./files/config/" # trailing / is important to copy only directory content and not the directory itself
    dest: "{{ xdg_config_home }}/aws"
    mode: "0600"

- name: Create shell config file in {{ shell_config_dir }}
  ansible.builtin.blockinfile:
    create: true
    marker: "# {mark} - ANSIBLE MANAGED BLOCK"
    insertbefore: BOF # Beginning of file
    path: "{{ shell_config_dir }}/{{ item | basename }}"
    block: "{{ lookup('ansible.builtin.file', './shell_config/{{ item | basename }}') }}"
    mode: "0600"
  loop: "{{ lookup('ansible.builtin.fileglob', './shell_config/*.zsh', wantlist=True) }}"
