---
- name: Install brew packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ javascript_brew_packages }}"

- name: Create shell config file in {{ shell_config_dir }}
  ansible.builtin.blockinfile:
    create: true
    marker: "# {mark} - ANSIBLE MANAGED BLOCK"
    insertbefore: BOF # Beginning of file
    path: "{{ shell_config_dir }}/nvm.zsh"
    block: "{{ lookup('ansible.builtin.file', './shell_config/nvm.zsh') }}"
    mode: "0600"
