---
- name: Install brew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  loop: "{{ git_brew_packages }}"

- name: Copy custom configuration to {{ xdg_config_home }}
  ansible.builtin.copy:
    src: "./files/config/" # trailing / is important to copy only directory content and not the directory itself
    dest: "{{ xdg_config_home }}"
    mode: "0600"

- name: Copy custom gitconfig to {{ xdg_config_home }}
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: "{{ xdg_config_home }}/git/config"
    mode: "0600"
