---
- name: Select macos package
  when: ansible_system == "Darwin"
  ansible.builtin.set_fact:
    git_package: "{{ git_brew_package }}"

- name: Select linux package
  when: ansible_system == "Linux"
  ansible.builtin.set_fact:
    git_package: "{{ git_linux_package }}"

- name: Install git
  ansible.builtin.package:
    name: "{{ git_package }}"
    state: latest
  become: "{{ ansible_system == 'Linux' }}"

- name: Copy Custom git configuration to {{ git_config_dir }}
  ansible.builtin.copy:
    src: "./files/"  # trailing / is important to copy only files within the directory
    dest: "{{ git_config_dir }}"
    mode: 0644

- name: Create a symbolic link to custom .gitconfig
  ansible.builtin.file:
    src: "{{ git_config_dir }}/gitconfig"
    dest: "~/.gitconfig"
    state: link
    mode: 0644
    force: true
