---
# See https://krew.sigs.k8s.io/docs/user-guide/setup/install/
- name: Install krew (kubectl plugin manager)
  shell: |
    mkdir -p ${HOME}/.config/krew
    export KREW_ROOT="${HOME}/.config/krew"
    (
    set -x; cd "$(mktemp -d)" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.{tar.gz,yaml}" &&
    tar zxvf krew.tar.gz &&
    KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" &&
    "$KREW" install --manifest=krew.yaml --archive=krew.tar.gz &&
    "$KREW" update
    )
