---
- name: Install brew packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  become: "{{ ansible_system == 'Linux' }}"
  loop: "{{ k8s_brew_packages }}"

- name: Install kubectl plugin manager
  ansible.builtin.import_tasks: ./krew_install.yml

- name: Copy custom configuration to {{ xdg_config_home }}
  ansible.builtin.copy:
    src: "./files/config/" # trailing / is important to copy only directory content and not the directory itself
    dest: "{{ xdg_config_home }}"
    mode: "0600"

- name: Create a symbolic link to custom .kube
  ansible.builtin.file:
    src: "{{ xdg_config_home }}/kube"
    dest: "~/.kube"
    state: link

- name: Create shell config file in {{ shell_config_dir }}
  ansible.builtin.blockinfile:
    create: true
    marker: "# {mark} - ANSIBLE MANAGED BLOCK"
    insertbefore: BOF # Beginning of file
    path: "{{ shell_config_dir }}/{{ item | basename }}"
    block: "{{ lookup('ansible.builtin.file', './shell_config/{{ item | basename }}') }}"
    mode: "0600"
  loop: "{{ lookup('ansible.builtin.fileglob', './shell_config/*.zsh', wantlist=True) }}"
