---
- name: Select macos package
  when: ansible_system == "Darwin"
  set_fact:
    k8s_packages: "{{ k8s_brew_packages }}"

- name: Select linux package
  when: ansible_system == "Linux"
  set_fact:
    k8s_packages: "{{ k8s_linux_packages }}"

- name: Install k8s tools
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ k8s_packages }}"

- name: Install k8s tools on linux (no package manager)
  when:
    - ansible_system == "Linux"
    - not k8s_linux_packages
  import_tasks: ./linux_install.yml

- name: Manage configuration file
  when: k8s_config_file != ""
  block:
    - name: Check config files exists
      stat:
        path: "{{ k8s_config_file }}"
      register: file_details

    - name: Ensure config files exists
      when: not file_details.stat.exists
      file:
        path: "{{ k8s_config_file }}"
        state: touch
        mode: 0600

    - name: Create config file
      blockinfile:
        marker: "# {mark} - K8S - ANSIBLE MANAGED BLOCK"
        insertafter: EOF
        path: "{{ k8s_config_file }}"
        block: |
          # Aliases
          alias k="kubectl"
          alias kx="kubectx"
          alias kn="kubens"

          # Completion
          if [[ "${SHELL}" =~ 'zsh' ]]; then
            source <(kubectl completion zsh)
            source <(stern --completion=zsh)
          fi
