---
- name: Install brew packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ terraform_brew_packages }}"

- name: Create shell config file in {{ shell_config_dir }}
  ansible.builtin.blockinfile:
    create: true
    marker: "# {mark} - ANSIBLE MANAGED BLOCK"
    insertbefore: BOF # Beginning of file
    path: "{{ shell_config_dir }}/terraform.zsh"
    block: "{{ lookup('ansible.builtin.file', './shell_config/terraform.zsh') }}"
    mode: "0600"
