---
- name: Add Homebrew third party repositories (taps)
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ terraform_brew_taps }}"

- name: Install brew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  loop: "{{ terraform_brew_packages }}"

- name: Create shell config file in {{ shell_config_dir }}
  ansible.builtin.blockinfile:
    create: true
    marker: "# {mark} - ANSIBLE MANAGED BLOCK"
    insertbefore: BOF # Beginning of file
    path: "{{ shell_config_dir }}/{{ item | basename }}"
    block: "{{ lookup('ansible.builtin.file', './shell_config/' + (item | basename)) }}"
    mode: "0600"
  loop: "{{ lookup('ansible.builtin.fileglob', './shell_config/*.zsh', wantlist=True) }}"

- name: Copy custom configuration to {{ xdg_config_home }}
  ansible.builtin.copy:
    src: "./files/config/" # trailing / is important to copy only directory content and not the directory itself
    dest: "{{ xdg_config_home }}/terraform"
    mode: "0600"

# The directory is NOT created by terraform itself
# WARNING: keep in sync with plugin_cache_dir in .terraformrc
- name: Create the terraform plugin cache directory
  ansible.builtin.file:
    path: ~/.terraform.d/plugin-cache
    state: directory
    mode: "0755"

- name: Create a symbolic link to custom .terraformrc
  ansible.builtin.file:
    src: "{{ xdg_config_home }}/terraform/.terraformrc"
    dest: "~/.terraformrc"
    state: link
