---
- name: Select macos packages
  when: ansible_system == "Darwin"
  set_fact:
    terraform_packages: "{{ terraform_brew_packages }}"

- name: Select linux packages
  when: ansible_system == "Linux"
  set_fact:
    terraform_packages: "{{ terraform_linux_packages }}"

- name: Install terraform tools
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ terraform_packages }}"

- name: Install terraform tools on linux (no package manager)
  when:
    - ansible_system == "Linux"
    - not terraform_linux_packages
  import_tasks: ./linux_install.yml

- name: Manage configuration file
  when: terraform_config_file != ""
  block:
    - name: Check config files exists
      stat:
        path: "{{ terraform_config_file }}"
      register: file_details

    - name: Ensure config files exists
      when: not file_details.stat.exists
      file:
        path: "{{ terraform_config_file }}"
        state: touch
        mode: 0600

    - name: Create config file
      blockinfile:
        marker: "# {mark} - TERRAFORM - ANSIBLE MANAGED BLOCK"
        insertafter: EOF
        path: "{{ terraform_config_file }}"
        block: |
          # Aliases
          alias tf="terraform"
          alias tfi="terraform import"
          alias tfw="terraform workspace"
          alias tfs="terraform state"
