# https://starship.rs/config/
# https://github.com/dracula/starship/blob/master/starship.toml

# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
$os\
$all\
$fill\
$cmd_duration\
$kubernetes\
$azure\
$aws\
$gcloud\
$line_break\
$character\
"""

[cmd_duration]
format = '[\[took $duration\]]($style) '

[line_break]
disabled = false

[fill]
disabled = false
symbol = ' '

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[directory]
disabled = false
truncation_length = 3
truncation_symbol = '[…]/'

[docker_context]
symbol = ' '

[os]
disabled = false
[os.symbols]
Windows = ' '
Macos = ' '
Linux = ' '
Ubuntu = ' '

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
symbol = '󱃾 '

[aws]
disabled = false
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = '󰸏 '

[azure]
disabled = false
format = '[$symbol($subscription)]($style) '
symbol = '󰠅 '

[gcloud]
disabled = false
format = '[$symbol$account(@$domain)(\($region\))]($style) '
symbol = '󱇶 '

[terraform]
disabled = false
format = '[$symbol$workspace]($style) '
symbol = '󱁢 '

[python]
disabled = false
symbol = ' '

[nodejs]
disabled = false
symbol = ' '

[env_var]
disabled = true

[package]
disabled = true

[battery]
full_symbol = ' '
charging_symbol = ' '
discharging_symbol = ' '
disabled = false
[[battery.display]]
threshold = 15
style = 'bold red'
[[battery.display]]
threshold = 40
style = 'bold yellow'
