---
k8s_brew_packages:
  - kubectl
  - kubectx
  - kubespy
  - derailed/k9s/k9s
  - helm
  - stern
k8s_linux_packages: []
k8s_config_file: ""
k8s_kubectl_krew_enabled: True
k8s_krew_config_dir: "{{ lookup('env', 'HOME') }}/.config/krew"
