---
- name: Select macos package
  when: ansible_system == "Darwin"
  ansible.builtin.set_fact:
    screen_package: "{{ screen_brew_package }}"

- name: Select linux package
  when: ansible_system == "Linux"
  ansible.builtin.set_fact:
    screen_package: "{{ screen_linux_package }}"

- name: Install screen
  ansible.builtin.package:
    name: "{{ screen_package }}"
    state: latest
  become: "{{ ansible_system == 'Linux' }}"

- name: Copy Custom zsh configuration to {{ screen_config_dir }}
  ansible.builtin.copy:
    src: "./files/"  # trailing / is important to copy only files within the directory
    dest: "{{ screen_config_dir }}"
    mode: 0644

- name: Create a symbolic link to custom screenrc
  ansible.builtin.file:
    src: "{{ screen_config_dir }}/.screenrc"
    dest: "~/.screenrc"
    state: link
