---
- name: Intall brew package
  community.general.homebrew_cask:
    name: "{{ iterm2_brew_cask_package }}"
    state: latest

- name: Apply MacOs configurations
  community.general.osx_defaults:
    domain: com.googlecode.iterm2
    key: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ iterm2_defaults }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name is defined
    - item.type is defined
    - item.value is defined
    - iterm2_defaults|length > 0
    - iterm2_domain is defined
