---
- name: Select macos package
  when: ansible_system == "Darwin"
  set_fact:
    vim_package: "{{ vim_brew_package }}"

- name: Select linux package
  when: ansible_system == "Linux"
  set_fact:
    vim_package: "{{ vim_linux_package }}"

- name: Install vim
  package:
    name: "{{ vim_package }}"
    state: latest
  become: "{{ true if ansible_system == 'Linux' else false }}"

- name: Copy Custom vim configuration to {{ vim_config_dir }}
  copy:
    src: "./files/"  # trailing / is important to copy only files within the directory
    dest: "{{ vim_config_dir }}"
    mode: 0644

- name: Create a symbolic link to custom .vimrc
  file:
    src: "{{ vim_config_dir }}/.vimrc"
    dest: "~/.vimrc"
    state: link
    mode: 0644
