---
- name: Install vim
  homebrew:
    name: "{{ vim_brew_package }}"
    state: present

- name: Copy Custom vim configuration to {{ vim_config_dir }}
  copy:
    src: "./files/" # trailing / is important to copy only files within the directory
    dest: "{{ vim_config_dir }}"
    mode: 0644

- name: Create a symbolic link to custom .vimrc
  file:
    src: "{{ vim_config_dir }}/.vimrc"
    dest: "~/.vimrc"
    state: link
    mode: 0644
