---
- name: Install brew packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: latest
  loop: "{{ vim_brew_packages }}"

- name: Copy custom configuration to {{ xdg_config_home }}
  ansible.builtin.copy:
    src: "./files/config/" # trailing / is important to copy only directory content and not the directory itself
    dest: "{{ xdg_config_home }}/vim"
    mode: "0600"

- name: Create a symbolic link to custom .vimrc
  ansible.builtin.file:
    src: "{{ xdg_config_home }}/vim/.vimrc"
    dest: "~/.vimrc"
    state: link
