---
- name: Install brew packages
  community.general.homebrew_cask:
    name: "{{ alacritty_brew_cask_package }}"
    state: latest
    install_options: "appdir=${HOME}/Applications,no-quarantine" # Install in user's Applications directory

- name: Copy Custom alacritty configuration to {{ xdg_config_home }}
  ansible.builtin.copy:
    src: "./files/config/" # trailing / is important to copy only files within the directory
    dest: "{{ xdg_config_home }}/alacritty"
    mode: "0600"

- name: Clone theme repository
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty-theme.git
    dest: "{{ xdg_config_home }}/alacritty/themes"
    single_branch: true
    version: master
