---
- name: Select macos package
  when: ansible_system == "Darwin"
  set_fact:
    gpg_package: "{{ gpg_brew_package }}"

- name: Select linux package
  when: ansible_system == "Linux"
  set_fact:
    gpg_package: "{{ gpg_linux_package }}"

- name: Install gpg
  package:
    name: "{{ gpg_package }}"
    state: latest

- name: Ansible check gpg directory exists
  stat:
    path: "{{ gpg_config_dir }}"
  register: directory_details

- name: Ensure gpg directory exists
  when: not (directory_details.stat.exists and directory_details.stat.isdir)
  file:
    path: "{{ gpg_config_dir }}"
    state: directory
    mode: 0700

- name: Create a symbolic link to custom .gnupg
  file:
    src: "{{ gpg_config_dir }}"
    dest: "~/.gnupg"
    state: link

- name: Copy Custom gpg configuration to {{ gpg_config_dir }}
  copy:
    src: "./files/" # trailing / is important to copy only files within the directory
    dest: "{{ gpg_config_dir }}"
    mode: 0600

- name: Manage configuration file
  when: gpg_shell_config_file != ""
  block:
    - name: Check config files exists
      stat:
        path: "{{ gpg_shell_config_file }}"
      register: file_details

    - name: Ensure config files exists
      when: not file_details.stat.exists
      file:
        path: "{{ gpg_shell_config_file }}"
        state: touch
        mode: 0600

    - name: Create config file
      blockinfile:
        marker: "# {mark} - GPG - ANSIBLE MANAGED BLOCK"
        insertafter: EOF
        path: "{{ gpg_shell_config_file }}"
        block: |
          # Aliases

          # Configure gpg
          if command -v gpg &>/dev/null; then
            if [[ "${SHELL}" =~ 'zsh' ]]; then
              export GPG_TTY=${TTY}
            else 
              export GPG_TTY=$(tty)
            fi
          fi
