---
- name: Setup workstation
  hosts: all
  gather_facts: true

  vars:
    shell_config_dir: "{{ lookup('env','HOME') }}/.config/zsh"

  tasks:
    - name: Update homebrew
      when: ansible_system == "Darwin"
      homebrew:
        update_homebrew: true
      tags:
        - homebrew-update

    - ansible.builtin.import_role:
        name: fonts
      tags:
        - fonts

    - ansible.builtin.import_role:
        name: python
      tags:
        - python

    - ansible.builtin.import_role:
        name: zsh
      vars:
        zsh_config_dir: "{{ shell_config_dir }}"
      tags:
        - zsh

    - ansible.builtin.import_role:
        name: git
      tags:
        - git

    - ansible.builtin.import_role:
        name: gnu_tools
      vars:
        gnu_tools_shell_config_file: "{{ shell_config_dir }}/custom/gnu-tools.zsh"
      when: ansible_system == "Darwin"
      tags:
        - gnu-tools

    - ansible.builtin.import_role:
        name: cli_tools
      vars:
        cli_tools_shell_config_file: "{{ shell_config_dir }}/custom/cli-tools.zsh"
      tags:
        - cli-tools

    - ansible.builtin.import_role:
        name: vim
      tags:
        - vim

    - ansible.builtin.import_role:
        name: screen
      tags:
        - screen

    - ansible.builtin.import_role:
        name: ssh
      tags:
        - ssh

    - ansible.builtin.import_role:
        name: gpg
      vars:
        gpg_shell_config_file: "{{ shell_config_dir }}/custom/gpg.zsh"
      tags:
        - gpg

    - ansible.builtin.import_role:
        name: kubernetes
      vars:
        k8s_shell_config_file: "{{ shell_config_dir }}/custom/kubernetes.zsh"
      tags:
        - kubernetes

    - ansible.builtin.import_role:
        name: terraform
      vars:
        terraform_shell_config_file: "{{ shell_config_dir }}/custom/terraform.zsh"
      tags:
        - terraform

    - ansible.builtin.import_role:
        name: azure
      vars:
        azure_shell_config_file: "{{ shell_config_dir }}/custom/azure.zsh"
      tags:
        - azure

    - ansible.builtin.import_role:
        name: javascript
      vars:
        javascript_shell_config_file: "{{ shell_config_dir }}/custom/javascript.zsh"
      tags:
        - javascript

    - ansible.builtin.import_role:
        name: iterm2
      vars:
        iterm2_defaults:
          - name: OnlyWhenMoreTabs
            type: string
            value: true
          - name: PromptOnQuit
            type: bool
            value: false
      when: ansible_system == "Darwin"
      tags:
        - iterm2
