---
- name: Setup workstation
  hosts: all
  gather_facts: True

  vars:
    shell_config_dir: "{{ lookup('env','HOME') }}/.config/zsh"

  tasks:
    - name: Update homebrew
      when: ansible_system == "Darwin"
      homebrew:
        update_homebrew: yes
      tags:
        - homebrew-update

    # - name: Install homebrew tap
    #   homebrew_tap:
    #     name: homebrew/cask-casks
    #     state: present
    #   tags:
    #     - homebrew-tap

    - import_role:
        name: python
      tags:
        - python

    - import_role:
        name: zsh
      vars:
        zsh_config_dir: "{{ shell_config_dir }}"
      tags:
        - zsh

    - import_role:
        name: gnu-tools
      vars:
        gnu_tools_config_file: "{{ shell_config_dir }}/custom/gnu-tools.zsh"
      when: ansible_system == "Darwin"
      tags:
        - gnu-tools

    - import_role:
        name: cli-tools
      tags:
        - cli-tools

    - import_role:
        name: vim
      tags:
        - vim

    - import_role:
        name: screen
      tags:
        - screen

    - import_role:
        name: ssh
      tags:
        - ssh

    - import_role:
        name: kubernetes
      vars:
        k8s_config_file: "{{ shell_config_dir }}/custom/kubernetes.zsh"
      tags:
        - kubernetes

    - import_role:
        name: terraform
      vars:
        terraform_config_file: "{{ shell_config_dir }}/custom/terraform.zsh"
      tags:
        - terraform

    - import_role:
        name: azure
      vars:
        azure_config_file: "{{ shell_config_dir }}/custom/azure.zsh"
      tags:
        - azure

    - import_role:
        name: javascript
      vars:
        javascript_config_file: "{{ shell_config_dir }}/custom/javascript.zsh"
      tags:
        - javascript

    - import_role:
        name: iterm2
      vars:
        iterm2_defaults:
          - name: OnlyWhenMoreTabs
            type: string
            value: true
          - name: PromptOnQuit
            type: bool
            value: false
      when: ansible_system == "Darwin"
      tags:
        - iterm2
