---
- name: Setup workstation
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Init Homebrew
      when: ansible_system == "Darwin"
      tags: always
      block:
        - name: Retrieve homebrew prefix
          ansible.builtin.shell: |
            brew --prefix
          register: brew_prefix
          changed_when: false

        - name: Register homebrew prefix as fact
          ansible.builtin.set_fact:
            homebrew_prefix: "{{ brew_prefix.stdout }}"

        - name: Disable homebrew analytics
          ansible.builtin.shell: |
            brew analytics off
          changed_when: false

        - name: Update homebrew
          community.general.homebrew:
            update_homebrew: true
          tags:
            - homebrew-update

        - ansible.builtin.debug:
            msg: |
              Homebrew Prefix: {{ homebrew_prefix }}

    - name: Install MacOs tools
      when: ansible_system == "Darwin"
      block:
        - ansible.builtin.import_role:
            name: fonts
          tags:
            - fonts

        - ansible.builtin.import_role:
            name: python
          tags:
            - python

        - ansible.builtin.import_role:
            name: zsh
          tags:
            - zsh

        - ansible.builtin.import_role:
            name: git
          tags:
            - git

        - ansible.builtin.import_role:
            name: cli_tools
          tags:
            - cli-tools

        - ansible.builtin.import_role:
            name: docker
          tags:
            - docker

        - ansible.builtin.import_role:
            name: vim
          tags:
            - vim

        - ansible.builtin.import_role:
            name: nvim
          tags:
            - nvim

        - ansible.builtin.import_role:
            name: ssh
          tags:
            - ssh

        - ansible.builtin.import_role:
            name: gpg
          tags:
            - gpg

        - ansible.builtin.import_role:
            name: kubernetes
          tags:
            - kubernetes

        - ansible.builtin.import_role:
            name: terraform
          tags:
            - terraform

        - ansible.builtin.import_role:
            name: azure
          tags:
            - azure

        - ansible.builtin.import_role:
            name: aws
          tags:
            - aws

        - ansible.builtin.import_role:
            name: gcloud
          tags:
            - gcloud

        - ansible.builtin.import_role:
            name: javascript
          tags:
            - javascript

        - ansible.builtin.import_role:
            name: iterm2
          tags:
            - iterm2

        - ansible.builtin.import_role:
            name: akamai
          tags:
            - akamai

        - ansible.builtin.import_role:
            name: alacritty
          tags:
            - alacritty
