---
name: Test

on:
  pull_request:
    paths:
      - playbooks/**
      - roles/**
      - ".github/workflows/*"

concurrency:
  group: test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  PYTHON_VERSION: 3.13

jobs:
  lint:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Create virtual environment
        run: |
          uv venv .venv --prompt "dotfiles_venv"

      - name: Install dependencies
        run: |
          # uv will install dependencies from restored cache if any
          uv sync --frozen

      - name: Run lint
        run: uv run ansible-lint

  deploy:
    needs: lint
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: true

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Create virtual environment
        run: |
          uv venv .venv --prompt "dotfiles_venv"

      - name: Install dependencies
        run: |
          # uv will install dependencies from restored cache if any
          uv sync --frozen

      - name: Cleanup Runner before install
        run: |
          rm -rf ${HOME}/.azure

      - name: Install playbook
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          uv run ansible-playbook playbooks/main.yml -vv
