---
- name: Install Homebrew tap cask-fonts
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install brew packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  loop: "{{ fonts_brew_cask_packages }}"
